name: Lint and Test
on:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        node-version: '16.x'
      - name: Install dependencies
        run: yarn
      - name: Run Linter
        run: yarn lint
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        node-version: '16.x'
      - name: Install dependencies
        run: yarn
      - name: Run Test
        run: yarn test
